In [2]:
import time

import torch

print(torch.__version__)

2.4.1+cu121


In [2]:
x = [1, 2, 3, 4, 5]
x = torch.as_tensor(x)
print(x)

tensor([1, 2, 3, 4, 5])


In [3]:
x = torch.zeros(3, 4)
print(x)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [ ]:
x = torch.ones(3, 4)
print(x)

In [4]:
x = torch.full((3, 4), fill_value=2)
print(x)

tensor([[2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2]])


In [5]:
x = torch.randn(3, 4)
print(x)

tensor([[-1.2763, -0.1338, -0.0251,  0.7181],
        [ 0.3210,  0.2507, -0.8210, -0.0495],
        [-0.2885,  0.2151,  1.3923, -0.0163]])


In [6]:
x = torch.randn(3, 4)
y = torch.zeros_like(x)
print(y)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [ ]:
x = torch.randn(3, 4)
y = torch.ones_like(x)
print(y)

In [ ]:
x = torch.randn(3, 4)
y = torch.full_like(x, 5)
print(y)

In [8]:
x = torch.zeros(3, 4, dtype=torch.bool)
print(x)
y = x.new_tensor([1, 2, 3, 4])
print(y)

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])
tensor([True, True, True, True])


In [9]:
x = torch.ones(5, 1)
y = torch.ones(1, 5)
z = x + y
print(z, z.shape)

tensor([[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]]) torch.Size([5, 5])


In [10]:
x = torch.ones(1, 1, 1, 1, 1)
y = torch.ones(2, 1, 3, 1, 2)
z = x + y
print(z, z.shape)

tensor([[[[[2., 2.]],

          [[2., 2.]],

          [[2., 2.]]]],



        [[[[2., 2.]],

          [[2., 2.]],

          [[2., 2.]]]]]) torch.Size([2, 1, 3, 1, 2])


In [13]:
x = torch.ones(3, 4, 5)
print(x.shape)
print(x.mean())
print(x.mean(-1))

torch.Size([3, 4, 5])
tensor(1.)
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [14]:
x = torch.ones(3, 4, 5)
y = x.sum(dim=0)
print(y, y.shape)
z= x.sum(dim=(1, 2))
print(z, z.shape)

tensor([[3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.]]) torch.Size([4, 5])
tensor([20., 20., 20.]) torch.Size([3])


In [15]:
x = torch.ones(3, 4, 5)
y = x.sum(dim=(1, 2))
z = x.sum(dim=(1, 2), keepdim=True)
print(y, y.shape)
print(z, z.shape)

tensor([20., 20., 20.]) torch.Size([3])
tensor([[[20.]],

        [[20.]],

        [[20.]]]) torch.Size([3, 1, 1])


In [2]:
x = torch.randn(5, 5)
print(x.to(torch.long))

tensor([[ 2, -1,  0,  1, -1],
        [ 0,  1,  0, -1,  0],
        [ 0,  0,  0, -1,  0],
        [ 1,  1,  1,  0,  0],
        [ 0,  3,  0, -1,  0]])


In [17]:
x = torch.randn(2, 3, 2)
print(x)
y = x.view(6, 2)
z = x.view(-1, 2) # it merges all the dimenation except the last dimension
print(y, y.shape)
print(z, z.shape)

tensor([[[-1.4017, -0.0961],
         [ 1.6133,  1.2955],
         [-1.0801,  0.5213]],

        [[ 1.1229, -0.7825],
         [-0.4720, -1.9570],
         [ 0.5692, -0.1081]]])
tensor([[-1.4017, -0.0961],
        [ 1.6133,  1.2955],
        [-1.0801,  0.5213],
        [ 1.1229, -0.7825],
        [-0.4720, -1.9570],
        [ 0.5692, -0.1081]]) torch.Size([6, 2])
tensor([[-1.4017, -0.0961],
        [ 1.6133,  1.2955],
        [-1.0801,  0.5213],
        [ 1.1229, -0.7825],
        [-0.4720, -1.9570],
        [ 0.5692, -0.1081]]) torch.Size([6, 2])


In [19]:
x = torch.randn(2, 3, 2)
print(x)
y = x.permute(1, 2, 0)
print(y, y.shape)

tensor([[[-0.6785,  0.5362],
         [-2.3543,  0.6461],
         [ 1.3214,  0.0963]],

        [[ 0.5708, -0.9465],
         [-0.4627, -0.1426],
         [-1.0063, -1.8437]]])
tensor([[[-0.6785,  0.5708],
         [ 0.5362, -0.9465]],

        [[-2.3543, -0.4627],
         [ 0.6461, -0.1426]],

        [[ 1.3214, -1.0063],
         [ 0.0963, -1.8437]]]) torch.Size([3, 2, 2])


In [20]:
x = torch.ones(2, 3)
y = torch.ones(2, 3)
z = torch.cat([x, y], dim=0)
print(z, z.shape)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) torch.Size([4, 3])


In [22]:
x = torch.ones(2, 3)
y = torch.ones(2, 3)
z = torch.stack([x, y], dim=1)
print(z, z.shape)

tensor([[1., 1., 1.],
        [1., 1., 1.]]) tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]]) torch.Size([2, 2, 3])


In [25]:
def add_two_lists(x, y):
    z = []
    for i, j in zip(x, y):
        z.append(i + j)
    return z


x = torch.ones(5000)
y = torch.ones(5000)
t1 = time.time()
z = add_two_lists(x, y)
print(f"{time.time() - t1:.4f} sec.")

0.1003 sec.


In [26]:
def add_two_lists(x, y):
    return x + y


x = torch.ones(5000)
y = torch.ones(5000)
t1 = time.time()
z = add_two_lists(x, y)
print(z.shape)
print(f"{time.time() - t1:.4f} sec.")

torch.Size([5000])
0.0143 sec.


In [1]:
import torch
x = torch.randn(3, 3)
y = torch.zeros(5, 2, dtype=torch.long)
print(x)
print(x.to(torch.float32))
print(x.to(torch.bool))
print(x.to(y))

tensor([[-1.3809,  0.4806,  0.2115],
        [ 0.9383,  1.1754,  1.4978],
        [-0.0591, -0.4828, -0.6148]])
tensor([[-1.3809,  0.4806,  0.2115],
        [ 0.9383,  1.1754,  1.4978],
        [-0.0591, -0.4828, -0.6148]])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])
tensor([[-1,  0,  0],
        [ 0,  1,  1],
        [ 0,  0,  0]])


In [3]:
x = torch.arange(8)
print(x)
y = torch.arange(2, 8)
print(y)
z = torch.arange(3, 10, step=2)
print(z)

tensor([0, 1, 2, 3, 4, 5, 6, 7])
tensor([2, 3, 4, 5, 6, 7])
tensor([3, 5, 7, 9])


In [15]:
x = torch.arange(0,12).view(3,4)
print(x)
x = torch.cumsum(x, 1)
print(x)
x = torch.cumsum(x, 0)
print(x)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 0,  1,  3,  6],
        [ 4,  9, 15, 22],
        [ 8, 17, 27, 38]])
tensor([[ 0,  1,  3,  6],
        [ 4, 10, 18, 28],
        [12, 27, 45, 66]])
